export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS'
export const LOAD_ABOUT_SUCCESS = 'LOAD_ABOUT_SUCCESS'
export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS'
export const LOAD_CHARTS_SUCCESS = 'LOAD_CHARTS_SUCCESS'
